apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-secrets-kv
  namespace: azure-golang
  labels:
    app: "azure-golang-app"
spec:
  parameters:
    keyvaultName: golang-vault
    objects: |
      array:
        - |
          objectName: pgsql-username
          objectType: secret
        - |
          objectName: pgsql-password
          objectType: secret
    resourceGroup: "aks-golang-application-nodes"  
    subscriptionId: ""
    tenantId: ""
    usePodIdentity: "true"
  provider: azure
  secretObjects:
  - secretName: username
    data:
    - key: PGSQL_USER
      objectName: pgsql-username
    type: Opaque
  - secretName: password
    data:
    - key: PGSQL_PASSWORD
      objectName: pgsql-password
    type: Opaque
